package models

type EuroJackpotResponse struct {
	Last struct {
		Nr       int    `json:"nr"`
		Currency string `json:"currency"`
		Date     struct {
			Full      string `json:"full"`
			Day       int    `json:"day"`
			Month     int    `json:"month"`
			Year      int    `json:"year"`
			Hour      int    `json:"hour"`
			Minute    int    `json:"minute"`
			DayOfWeek string `json:"dayOfWeek"`
		} `json:"date"`
		ClosingDate             string `json:"closingDate"`
		LateClosingDate         string `json:"lateClosingDate"`
		DrawingDate             string `json:"drawingDate"`
		Numbers                 []int  `json:"numbers"`
		EuroNumbers             []int  `json:"euroNumbers"`
		Jackpot                 string `json:"jackpot"`
		MarketingJackpot        string `json:"marketingJackpot"`
		SpecialMarketingJackpot string `json:"specialMarketingJackpot"`
		ClimbedSince            int    `json:"climbedSince"`
		Winners                 int    `json:"Winners"`
		Odds                    struct {
			Rank0 struct {
				Winners      int `json:"winners"`
				SpecialPrize int `json:"specialPrize"`
				Prize        int `json:"prize"`
			} `json:"rank0"`
			Rank1 struct {
				Winners      int `json:"winners"`
				SpecialPrize int `json:"specialPrize"`
				Prize        int `json:"prize"`
			} `json:"rank1"`
			Rank2 struct {
				Winners      int `json:"winners"`
				SpecialPrize int `json:"specialPrize"`
				Prize        int `json:"prize"`
			} `json:"rank2"`
			Rank3 struct {
				Winners      int `json:"winners"`
				SpecialPrize int `json:"specialPrize"`
				Prize        int `json:"prize"`
			} `json:"rank3"`
			Rank8 struct {
				Winners      int `json:"winners"`
				SpecialPrize int `json:"specialPrize"`
				Prize        int `json:"prize"`
			} `json:"rank8"`
			Rank9 struct {
				Winners      int `json:"winners"`
				SpecialPrize int `json:"specialPrize"`
				Prize        int `json:"prize"`
			} `json:"rank9"`
			Rank10 struct {
				Winners      int `json:"winners"`
				SpecialPrize int `json:"specialPrize"`
				Prize        int `json:"prize"`
			} `json:"rank10"`
			Rank4 struct {
				Winners      int `json:"winners"`
				SpecialPrize int `json:"specialPrize"`
				Prize        int `json:"prize"`
			} `json:"rank4"`
			Rank5 struct {
				Winners      int `json:"winners"`
				SpecialPrize int `json:"specialPrize"`
				Prize        int `json:"prize"`
			} `json:"rank5"`
			Rank6 struct {
				Winners      int `json:"winners"`
				SpecialPrize int `json:"specialPrize"`
				Prize        int `json:"prize"`
			} `json:"rank6"`
			Rank11 struct {
				Winners      int `json:"winners"`
				SpecialPrize int `json:"specialPrize"`
				Prize        int `json:"prize"`
			} `json:"rank11"`
			Rank7 struct {
				Winners      int `json:"winners"`
				SpecialPrize int `json:"specialPrize"`
				Prize        int `json:"prize"`
			} `json:"rank7"`
			Rank12 struct {
				Winners      int `json:"winners"`
				SpecialPrize int `json:"specialPrize"`
				Prize        int `json:"prize"`
			} `json:"rank12"`
		} `json:"odds"`
	} `json:"last"`
	Next struct {
		Nr       int    `json:"nr"`
		Currency string `json:"currency"`
		Date     struct {
			Full      string `json:"full"`
			Day       int    `json:"day"`
			Month     int    `json:"month"`
			Year      int    `json:"year"`
			Hour      int    `json:"hour"`
			Minute    int    `json:"minute"`
			DayOfWeek string `json:"dayOfWeek"`
		} `json:"date"`
		ClosingDate             string `json:"closingDate"`
		LateClosingDate         string `json:"lateClosingDate"`
		DrawingDate             string `json:"drawingDate"`
		Jackpot                 string `json:"jackpot"`
		MarketingJackpot        string `json:"marketingJackpot"`
		SpecialMarketingJackpot string `json:"specialMarketingJackpot"`
		ClimbedSince            int    `json:"climbedSince"`
	} `json:"next"`
}

type EuroExchangeRateResponse struct {
	Date string `json:"date"`
	Eur  struct {
		OneInch float64 `json:"1inch"`
		Aave    float64 `json:"aave"`
		Ada     float64 `json:"ada"`
		Aed     float64 `json:"aed"`
		Afn     float64 `json:"afn"`
		Algo    float64 `json:"algo"`
		All     float64 `json:"all"`
		Amd     float64 `json:"amd"`
		Amp     float64 `json:"amp"`
		Ang     float64 `json:"ang"`
		Aoa     float64 `json:"aoa"`
		Ar      float64 `json:"ar"`
		Ars     float64 `json:"ars"`
		Atom    float64 `json:"atom"`
		Aud     float64 `json:"aud"`
		Avax    float64 `json:"avax"`
		Awg     float64 `json:"awg"`
		Axs     float64 `json:"axs"`
		Azn     float64 `json:"azn"`
		Bam     float64 `json:"bam"`
		Bat     float64 `json:"bat"`
		Bbd     float64 `json:"bbd"`
		Bch     float64 `json:"bch"`
		Bdt     float64 `json:"bdt"`
		Bgn     float64 `json:"bgn"`
		Bhd     float64 `json:"bhd"`
		Bif     float64 `json:"bif"`
		Bmd     float64 `json:"bmd"`
		Bnb     float64 `json:"bnb"`
		Bnd     float64 `json:"bnd"`
		Bob     float64 `json:"bob"`
		Brl     float64 `json:"brl"`
		Bsd     float64 `json:"bsd"`
		Bsv     float64 `json:"bsv"`
		Bsw     float64 `json:"bsw"`
		Btc     float64 `json:"btc"`
		Btcb    float64 `json:"btcb"`
		Btg     float64 `json:"btg"`
		Btn     float64 `json:"btn"`
		Busd    float64 `json:"busd"`
		Bwp     float64 `json:"bwp"`
		Byn     float64 `json:"byn"`
		Byr     float64 `json:"byr"`
		Bzd     float64 `json:"bzd"`
		Cad     float64 `json:"cad"`
		Cake    float64 `json:"cake"`
		Cdf     float64 `json:"cdf"`
		Celo    float64 `json:"celo"`
		Chf     float64 `json:"chf"`
		Chz     float64 `json:"chz"`
		Clf     float64 `json:"clf"`
		Clp     float64 `json:"clp"`
		Cny     float64 `json:"cny"`
		Comp    float64 `json:"comp"`
		Cop     float64 `json:"cop"`
		Crc     float64 `json:"crc"`
		Cro     float64 `json:"cro"`
		Crv     float64 `json:"crv"`
		Cuc     float64 `json:"cuc"`
		Cup     float64 `json:"cup"`
		Cve     float64 `json:"cve"`
		Cvx     float64 `json:"cvx"`
		Czk     float64 `json:"czk"`
		Dai     float64 `json:"dai"`
		Dash    float64 `json:"dash"`
		Dcr     float64 `json:"dcr"`
		Dfi     float64 `json:"dfi"`
		Djf     float64 `json:"djf"`
		Dkk     float64 `json:"dkk"`
		Doge    float64 `json:"doge"`
		Dop     float64 `json:"dop"`
		Dot     float64 `json:"dot"`
		Dzd     float64 `json:"dzd"`
		Egld    float64 `json:"egld"`
		Egp     float64 `json:"egp"`
		Enj     float64 `json:"enj"`
		Eos     float64 `json:"eos"`
		Ern     float64 `json:"ern"`
		Etb     float64 `json:"etb"`
		Etc     float64 `json:"etc"`
		Eth     float64 `json:"eth"`
		Eur     int     `json:"eur"`
		Fei     float64 `json:"fei"`
		Fil     float64 `json:"fil"`
		Fjd     float64 `json:"fjd"`
		Fkp     float64 `json:"fkp"`
		Flow    float64 `json:"flow"`
		Frax    float64 `json:"frax"`
		Ftm     float64 `json:"ftm"`
		Ftt     float64 `json:"ftt"`
		Gala    float64 `json:"gala"`
		Gbp     float64 `json:"gbp"`
		Gel     float64 `json:"gel"`
		Ggp     float64 `json:"ggp"`
		Ghs     float64 `json:"ghs"`
		Gip     float64 `json:"gip"`
		Gmd     float64 `json:"gmd"`
		Gnf     float64 `json:"gnf"`
		Gno     float64 `json:"gno"`
		Grt     float64 `json:"grt"`
		Gt      float64 `json:"gt"`
		Gtq     float64 `json:"gtq"`
		Gyd     float64 `json:"gyd"`
		Hbar    float64 `json:"hbar"`
		Hkd     float64 `json:"hkd"`
		Hnl     float64 `json:"hnl"`
		Hnt     float64 `json:"hnt"`
		Hot     float64 `json:"hot"`
		Hrk     float64 `json:"hrk"`
		Ht      float64 `json:"ht"`
		Htg     float64 `json:"htg"`
		Huf     float64 `json:"huf"`
		Icp     float64 `json:"icp"`
		Idr     float64 `json:"idr"`
		Ils     float64 `json:"ils"`
		Imp     float64 `json:"imp"`
		Inj     float64 `json:"inj"`
		Inr     float64 `json:"inr"`
		Iqd     float64 `json:"iqd"`
		Irr     float64 `json:"irr"`
		Isk     float64 `json:"isk"`
		Jep     float64 `json:"jep"`
		Jmd     float64 `json:"jmd"`
		Jod     float64 `json:"jod"`
		Jpy     float64 `json:"jpy"`
		Kava    float64 `json:"kava"`
		Kcs     float64 `json:"kcs"`
		Kda     float64 `json:"kda"`
		Kes     float64 `json:"kes"`
		Kgs     float64 `json:"kgs"`
		Khr     float64 `json:"khr"`
		Klay    float64 `json:"klay"`
		Kmf     float64 `json:"kmf"`
		Knc     float64 `json:"knc"`
		Kpw     float64 `json:"kpw"`
		Krw     float64 `json:"krw"`
		Ksm     float64 `json:"ksm"`
		Kwd     float64 `json:"kwd"`
		Kyd     float64 `json:"kyd"`
		Kzt     float64 `json:"kzt"`
		Lak     float64 `json:"lak"`
		Lbp     float64 `json:"lbp"`
		Leo     float64 `json:"leo"`
		Link    float64 `json:"link"`
		Lkr     float64 `json:"lkr"`
		Lrc     float64 `json:"lrc"`
		Lrd     float64 `json:"lrd"`
		Lsl     float64 `json:"lsl"`
		Ltc     float64 `json:"ltc"`
		Ltl     float64 `json:"ltl"`
		Luna    float64 `json:"luna"`
		Lvl     float64 `json:"lvl"`
		Lyd     float64 `json:"lyd"`
		Mad     float64 `json:"mad"`
		Mana    float64 `json:"mana"`
		Matic   float64 `json:"matic"`
		Mdl     float64 `json:"mdl"`
		Mga     float64 `json:"mga"`
		Mina    float64 `json:"mina"`
		Miota   float64 `json:"miota"`
		Mkd     float64 `json:"mkd"`
		Mkr     float64 `json:"mkr"`
		Mmk     float64 `json:"mmk"`
		Mnt     float64 `json:"mnt"`
		Mop     float64 `json:"mop"`
		Mro     float64 `json:"mro"`
		Mur     float64 `json:"mur"`
		Mvr     float64 `json:"mvr"`
		Mwk     float64 `json:"mwk"`
		Mxn     float64 `json:"mxn"`
		Myr     float64 `json:"myr"`
		Mzn     float64 `json:"mzn"`
		Nad     float64 `json:"nad"`
		Near    float64 `json:"near"`
		Neo     float64 `json:"neo"`
		Nexo    float64 `json:"nexo"`
		Ngn     float64 `json:"ngn"`
		Nio     float64 `json:"nio"`
		Nok     float64 `json:"nok"`
		Npr     float64 `json:"npr"`
		Nzd     float64 `json:"nzd"`
		Okb     float64 `json:"okb"`
		Omr     float64 `json:"omr"`
		One     float64 `json:"one"`
		Pab     float64 `json:"pab"`
		Paxg    float64 `json:"paxg"`
		Pen     float64 `json:"pen"`
		Pgk     float64 `json:"pgk"`
		Php     float64 `json:"php"`
		Pkr     float64 `json:"pkr"`
		Pln     float64 `json:"pln"`
		Pyg     float64 `json:"pyg"`
		Qar     float64 `json:"qar"`
		Qnt     float64 `json:"qnt"`
		Qtum    float64 `json:"qtum"`
		Ron     float64 `json:"ron"`
		Rsd     float64 `json:"rsd"`
		Rub     float64 `json:"rub"`
		Rune    float64 `json:"rune"`
		Rwf     float64 `json:"rwf"`
		Sand    float64 `json:"sand"`
		Sar     float64 `json:"sar"`
		Sbd     float64 `json:"sbd"`
		Scr     float64 `json:"scr"`
		Sdg     float64 `json:"sdg"`
		Sek     float64 `json:"sek"`
		Sgd     float64 `json:"sgd"`
		Shib    float64 `json:"shib"`
		Shp     float64 `json:"shp"`
		Sle     float64 `json:"sle"`
		Sll     float64 `json:"sll"`
		Sol     float64 `json:"sol"`
		Sos     float64 `json:"sos"`
		Srd     float64 `json:"srd"`
		Std     float64 `json:"std"`
		Stx     float64 `json:"stx"`
		Svc     float64 `json:"svc"`
		Syp     float64 `json:"syp"`
		Szl     float64 `json:"szl"`
		Thb     float64 `json:"thb"`
		Theta   float64 `json:"theta"`
		Tjs     float64 `json:"tjs"`
		Tmt     float64 `json:"tmt"`
		Tnd     float64 `json:"tnd"`
		Top     float64 `json:"top"`
		Trx     float64 `json:"trx"`
		Try     float64 `json:"try"`
		Ttd     float64 `json:"ttd"`
		Ttt     float64 `json:"ttt"`
		Tusd    float64 `json:"tusd"`
		Twd     float64 `json:"twd"`
		Tzs     float64 `json:"tzs"`
		Uah     float64 `json:"uah"`
		Ugx     float64 `json:"ugx"`
		Uni     float64 `json:"uni"`
		Usd     float64 `json:"usd"`
		Usdc    float64 `json:"usdc"`
		Usdp    float64 `json:"usdp"`
		Usdt    float64 `json:"usdt"`
		Uyu     float64 `json:"uyu"`
		Uzs     float64 `json:"uzs"`
		Vef     float64 `json:"vef"`
		Ves     float64 `json:"ves"`
		Vet     float64 `json:"vet"`
		Vnd     float64 `json:"vnd"`
		Vuv     float64 `json:"vuv"`
		Waves   float64 `json:"waves"`
		Wbtc    float64 `json:"wbtc"`
		Wemix   float64 `json:"wemix"`
		Wst     float64 `json:"wst"`
		Xaf     float64 `json:"xaf"`
		Xag     float64 `json:"xag"`
		Xau     float64 `json:"xau"`
		Xcd     float64 `json:"xcd"`
		Xch     float64 `json:"xch"`
		Xdc     float64 `json:"xdc"`
		Xdr     float64 `json:"xdr"`
		Xec     float64 `json:"xec"`
		Xem     float64 `json:"xem"`
		Xlm     float64 `json:"xlm"`
		Xmr     float64 `json:"xmr"`
		Xof     float64 `json:"xof"`
		Xpf     float64 `json:"xpf"`
		Xrp     float64 `json:"xrp"`
		Xtz     float64 `json:"xtz"`
		Yer     float64 `json:"yer"`
		Zar     float64 `json:"zar"`
		Zec     float64 `json:"zec"`
		Zil     float64 `json:"zil"`
		Zmk     float64 `json:"zmk"`
		Zmw     float64 `json:"zmw"`
		Zwl     float64 `json:"zwl"`
	} `json:"eur"`
}
